<?php
if ($match_data['Payment_before']) {
    $stmt = $conn->prepare("
	UPDATE $table_matches 
        SET Banka_ucet_cislo = ?,
   	 Banka_ucet_kod = ?,
   	 Banka_nazev = ?,
   	 Banka_adresa = ?,
   	 Klub_web = ?,
   	 Zavod = ?,
   	 Zavod_datum = ?,
   	 Zavod_cas_registrace_zacatek = ?,
   	 Zavod_cas_registrace_konec = ?,
   	 Zavod_zacatek_registrace = ?,
   	 Zavod_konec_registrace = ?,
   	 Zavod_registrace_pozastaveno = ?,
   	 Zavod_registrace_hromadna = ?,
     Zavod_registrace_smeny = ?,
   	 Zavod_more_divisions = ?,
   	 Zavod_zobrazovat_sponzory = ?,
     Zavod_obcansky_prukaz = ?,
   	 Zavod_zbrojni_prukaz = ?,
   	 Zavod_cislo_zbrane = ?,
     Zavod_nazev_zbrane = ?,
     Zavod_platba_volitelna = ?,
   	 Web_zobrazovat_discipliny = ?,
   	 Web_zobrazovat_aliasy = ?,
   	 Web_zobrazovat_vysledky = ?,
   	 Web_zobrazovat_zavodniky = ?,
   	 Web_zobrazovat_prehledy = ?,
   	 Zavod_cas_prematch = ?,
   	 Zavod_cas_prezence = ?,
   	 Zavod_cas_main = ?,
   	 Zavod_cas_main_dopoledne = ?,
   	 Zavod_cas_main_odpoledne = ?,
   	 Zavod_misto = ?,
   	 Zavod_misto_mapa = ?,
   	 Zavod_poradatel = ?,
   	 Zavod_poradatel_adresa = ?,
   	 Zavod_match_director = ?,
   	 Zavod_email_poradatel = ?,
   	 Zavod_telefon_poradatel = ?,
   	 Zavod_range_master = ?,
   	 Zavod_email_range_master = ?,
   	 Zavod_telefon_range_master = ?,
   	 Zavod_stats = ?,
   	 Zavod_email_stats = ?,
   	 Zavod_telefon_stats = ?,
   	 Zavod_hospodar = ?,
   	 Zavod_email_hospodar = ?,
   	 Zavod_telefon_hospodar = ?,
   	 Zavod_email_from = ?,
   	 Zavod_stages = ?,
     Pocet_smen = ?,
   	 Zavod_min_pocet_ran = ?,
   	 Zavod_pocet_dni_na_platbu = ?,
   	 Zavod_vysledky = ?,
   	 Zavod_propozice = ?,
   	 Squad_main_max = ?,
   	 Squad_prem_max = ?,
   	 Payment_before = ?
    WHERE Zavod_id = ?
    ");
    $stmt->bind_param(
        "sssssssssssissssssssiiiiisssssssssssssssssssssssiiiissiiss",
        $_POST['Banka_ucet_cislo'],
        $_POST['Banka_ucet_kod'],
        $_POST['Banka_nazev'],
        $_POST['Banka_adresa'],
        $_POST['Klub_web'],
        $_POST['Zavod'],
        $_POST['Zavod_datum'],
        $_POST['Zavod_cas_registrace_zacatek'],
        $_POST['Zavod_cas_registrace_konec'],
        $_POST['Zavod_zacatek_registrace'],
        $_POST['Zavod_konec_registrace'],
        $_POST['Zavod_registrace_pozastaveno'],
        $_POST['Zavod_registrace_hromadna'],
        $_POST['Zavod_registrace_smeny'],
        $_POST['Zavod_more_divisions'],
        $_POST['Zavod_zobrazovat_sponzory'],
        $_POST['Zavod_obcansky_prukaz'],
        $_POST['Zavod_zbrojni_prukaz'],
        $_POST['Zavod_cislo_zbrane'],
        $_POST['Zavod_nazev_zbrane'],
        $_POST['Zavod_platba_volitelna'],
        $_POST['Web_zobrazovat_discipliny'],
        $_POST['Web_zobrazovat_aliasy'],
        $_POST['Web_zobrazovat_vysledky'],
        $_POST['Web_zobrazovat_zavodniky'],
        $_POST['Web_zobrazovat_prehledy'],
        $_POST['Zavod_cas_prematch'],
        $_POST['Zavod_cas_prezence'],
        $_POST['Zavod_cas_main'],
        $_POST['Zavod_cas_main_dopoledne'],
        $_POST['Zavod_cas_main_odpoledne'],
        $_POST['Zavod_misto'],
        $_POST['Zavod_misto_mapa'],
        $_POST['Zavod_poradatel'],
        $_POST['Zavod_poradatel_adresa'],
        $_POST['Zavod_match_director'],
        $_POST['Zavod_email_poradatel'],
        $_POST['Zavod_telefon_poradatel'],
        $_POST['Zavod_range_master'],
        $_POST['Zavod_email_range_master'],
        $_POST['Zavod_telefon_range_master'],
        $_POST['Zavod_stats'],
        $_POST['Zavod_email_stats'],
        $_POST['Zavod_telefon_stats'],
        $_POST['Zavod_hospodar'],
        $_POST['Zavod_email_hospodar'],
        $_POST['Zavod_telefon_hospodar'],
        $_POST['Zavod_email_from'],
        $_POST['Zavod_stages'],
        $_POST['Pocet_smen'],
        $_POST['Zavod_min_pocet_ran'],
        $_POST['Zavod_pocet_dni_na_platbu'],
        $_POST['Zavod_vysledky'],
        $_POST['Zavod_propozice'],
        $_POST['Squad_main_max'],
        $_POST['Squad_prem_max'],
        $_POST['Payment_before'],
        $table
    );
} else {
    $stmt = $conn->prepare("
	UPDATE $table_matches 
            SET Banka_ucet_cislo = ?,
   	 Banka_ucet_kod = ?,
     Klub_web = ?,
     Zavod = ?,
     Zavod_datum = ?,
     Zavod_cas_registrace_zacatek = ?,
     Zavod_cas_registrace_konec = ?,
     Zavod_zacatek_registrace = ?,
     Zavod_konec_registrace = ?,
     Zavod_registrace_pozastaveno = ?,
     Zavod_registrace_hromadna = ?,
     Zavod_registrace_smeny = ?,
     Zavod_more_divisions = ?,
     Zavod_zobrazovat_sponzory = ?,
     Zavod_obcansky_prukaz = ?,
     Zavod_zbrojni_prukaz = ?,
     Zavod_cislo_zbrane = ?,
     Zavod_nazev_zbrane = ?,
     Zavod_platba_volitelna = ?,
     Web_zobrazovat_discipliny = ?,
     Web_zobrazovat_aliasy = ?,
     Web_zobrazovat_vysledky = ?,
   	 Web_zobrazovat_zavodniky = ?,
   	 Web_zobrazovat_prehledy = ?,
     Zavod_cas_prematch = ?,
     Zavod_cas_prezence = ?,
     Zavod_cas_main = ?,
     Zavod_cas_main_dopoledne = ?,
     Zavod_cas_main_odpoledne = ?,
     Zavod_misto = ?,
     Zavod_misto_mapa = ?,
     Zavod_poradatel = ?,
     Zavod_poradatel_adresa = ?,
     Zavod_match_director = ?,
     Zavod_email_poradatel = ?,
     Zavod_telefon_poradatel = ?,
     Zavod_range_master = ?,
     Zavod_email_range_master = ?,
     Zavod_telefon_range_master = ?,
     Zavod_stats = ?,
     Zavod_email_stats = ?,
     Zavod_telefon_stats = ?,
     Zavod_hospodar = ?,
     Zavod_email_hospodar = ?,
     Zavod_telefon_hospodar = ?,
     Zavod_email_from = ?,
     Zavod_stages = ?,
     Pocet_smen = ?,
     Zavod_min_pocet_ran = ?,
     Zavod_pocet_dni_na_platbu = ?,
     Zavod_vysledky = ?,
     Zavod_propozice = ?,
     Squad_main_max = ?,
     Squad_prem_max = ?,
     Payment_before = ?
    WHERE Zavod_id = ?
    ");
    $stmt->bind_param(
        "sssssssssissssssssssiiiisssssssssssssssssssssssiiissiiss",
        $_POST['Banka_ucet_cislo'],
        $_POST['Banka_ucet_kod'],
        $_POST['Klub_web'],
        $_POST['Zavod'],
        $_POST['Zavod_datum'],
        $_POST['Zavod_cas_registrace_zacatek'],
        $_POST['Zavod_cas_registrace_konec'],
        $_POST['Zavod_zacatek_registrace'],
        $_POST['Zavod_konec_registrace'],
        $_POST['Zavod_registrace_pozastaveno'],
        $_POST['Zavod_registrace_hromadna'],
        $_POST['Zavod_registrace_smeny'],
        $_POST['Zavod_more_divisions'],
        $_POST['Zavod_zobrazovat_sponzory'],
        $_POST['Zavod_obcansky_prukaz'],
        $_POST['Zavod_zbrojni_prukaz'],
        $_POST['Zavod_cislo_zbrane'],
        $_POST['Zavod_nazev_zbrane'],
        $_POST['Zavod_platba_volitelna'],
        $_POST['Web_zobrazovat_discipliny'],
        $_POST['Web_zobrazovat_aliasy'],
        $_POST['Web_zobrazovat_vysledky'],
        $_POST['Web_zobrazovat_zavodniky'],
        $_POST['Web_zobrazovat_prehledy'],
        $_POST['Zavod_cas_prematch'],
        $_POST['Zavod_cas_prezence'],
        $_POST['Zavod_cas_main'],
        $_POST['Zavod_cas_main_dopoledne'],
        $_POST['Zavod_cas_main_odpoledne'],
        $_POST['Zavod_misto'],
        $_POST['Zavod_misto_mapa'],
        $_POST['Zavod_poradatel'],
        $_POST['Zavod_poradatel_adresa'],
        $_POST['Zavod_match_director'],
        $_POST['Zavod_email_poradatel'],
        $_POST['Zavod_telefon_poradatel'],
        $_POST['Zavod_range_master'],
        $_POST['Zavod_email_range_master'],
        $_POST['Zavod_telefon_range_master'],
        $_POST['Zavod_stats'],
        $_POST['Zavod_email_stats'],
        $_POST['Zavod_telefon_stats'],
        $_POST['Zavod_hospodar'],
        $_POST['Zavod_email_hospodar'],
        $_POST['Zavod_telefon_hospodar'],
        $_POST['Zavod_email_from'],
        $_POST['Zavod_stages'],
        $_POST['Pocet_smen'],
        $_POST['Zavod_min_pocet_ran'],
        $_POST['Zavod_pocet_dni_na_platbu'],
        $_POST['Zavod_vysledky'],
        $_POST['Zavod_propozice'],
        $_POST['Squad_main_max'],
        $_POST['Squad_prem_max'],
        $_POST['Payment_before'],
        $table
    );
}
$stmt->execute();
session_start();
if ($stmt->errno !== 0) {
    include './components/modal-warning.php';
    WarningModal(
        "danger",
        "Chyba databáze",
        "index.php",
        "Při vkládání do databáze došlo k chybě!",
        "Kontaktujte <a href='mailto:" . htmlspecialchars($vyvojar, ENT_QUOTES, 'UTF-8') . "?subject=" . htmlspecialchars($match_data['Zavod'], ENT_QUOTES, 'UTF-8') . " - chyba aktualizace databáze [$table]'>vývojáře</a> registračního systému.",
        "Zpět do administrace"
    );
} elseif ($stmt->affected_rows === 0) {
    $_SESSION['toast'] = [
        'type' => 'primary',
        'message' => 'V nastavení závodu jste neprovedli žádné změny.',
        'duration' => 2000
    ];
} else {
    logAction("match data update");
    $_SESSION['toast'] = [
        'type' => 'success',
        'message' => 'Změny nastavení závodu byly úspěšně uloženy.',
        'duration' => 2500
    ];
}
$stmt->close();
header("Location: /");
exit();
